using System;
using System.Collections.Generic;
using System.Text;

namespace recopa_types
{
    public enum DocumentField
    {
        NULL = 0,
        TEM_CPF,
        ESTRANGEIRO,
        PROFISSIONAL_SAUDE,
        PROFISSIONAL_SEGURANCA,
        SEXO,
        RACA,
        SINTOMAS,
        CONDICOES,
        ESTADO_TESTE,
        TIPO_TESTE,
        RESULTADO_TESTE,
        CLASSIFICACAO_FINAL,
        EVOLUCAO_CASO,
    }

    public enum OptionsField
    {
        NULL = 0,
        TEM_CPF_SIM,
        TEM_CPF_NAO,
        ESTRANGEIRO_SIM,
        ESTRANGEIRO_NAO,
        PROFISSIONAL_SAUDE_SIM,
        PROFISSIONAL_SAUDE_NAO,
        PROFISSIONAL_SEGURANCA_SIM,
        PROFISSIONAL_SEGURANCA_NAO,
        SEXO_MASC,
        SEXO_FEM,
        RACA_BRANCA,
        RACA_PRETA,
        RACA_AMARELA,
        RACA_PARDA,
        RACA_INDIGENA,
        SINTOMAS_FEBRE,
        SINTOMAS_DOR_GARGANTA,
        SINTOMAS_TOSSE,
        SINTOMAS_DISPNEIA,
        SINTOMAS_OUTROS,
        CONDICOES_DOENCAS_RESPIRATORIAS,
        CONDICOES_DOENCAS_RENAIS,
        CONDICOES_DOENCAS_CROMOSSOMICA,
        CONDICOES_DIABETES,
        CONDICOES_IMUNOSSUPRESSAO,
        CONDICOES_DOENCAS_CARDIACAS,
        CONDICOES_GESTANTE,
        TIPO_TESTE_PCR,
        TIPO_TESTE_ANTICORPO,
        TIPO_TESTE_ANTIGENO,
        TIPO_TESTE_ELISA,
        TIPO_TESTE_ECLIA,
        RESULTADO_TESTE_POSITIVO,
        RESULTADO_TESTE_NEGATIVO,
        CLASSIFICACAO_FINAL_DESCARTADO,
        CLASSIFICACAO_FINAL_CONFIRMADO_EPIDEMIOLOGICO,
        CLASSIFICACAO_FINAL_CONFIRMADO_LABORATORIAL,
        CLASSIFICACAO_FINAL_CONFIRMADO_IMAGEM,
        CLASSIFICACAO_FINAL_CONFIRMADO_CRITERIO,
        CLASSIFICACAO_FINAL_SINDROME_GRIPAL,
        EVOLUCAO_CASO_CANCELADO,
        EVOLUCAO_CASO_IGNORADO,
        EVOLUCAO_CASO_TRATAMENTO,
        EVOLUCAO_CASO_INTERNADO,
        EVOLUCAO_CASO_UTI,
        EVOLUCAO_CASO_OBITO,
        EVOLUCAO_CASO_CURA,
        ESTADO_TESTE_SOLICITADO,
        ESTADO_TESTE_COLETADO,
        ESTADO_TESTE_CONCLUIDO,
        ESTADO_TESTE_NAO_SOLICITADO
    }
    class Enumerations
    {
    }
}
