name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Build and push image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: 'Build and Push: document-ml-predict'
      run: |
        cd document-ml-predict
        docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/document-ml-predict:${{ github.sha }}
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/document-ml-predict:${{ github.sha }}
        
    - name: 'Build and Push: image-cloud-processor'
      run: |
        cd image-cloud-processor
        docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/image-cloud-processor:${{ github.sha }}
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/image-cloud-processor:${{ github.sha }}
